# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            NickT's things
tagline:          'Nick\'s stuff'
description:      'A collection of things I\'ve created.'
url:              http://nickt.com.au
baseurl:          /

author:
  name:           'Nick Triantafillou'
  url:            https://twitter.com/xelfer

paginate:         10



