# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Nick\'s things
tagline:          "Nicks stuff"
description:      "A collection of things Ive created.
url:              http://nickt.com.au
baseurl:          /

author:
  name:           'Nick Triantafillou'
  url:            https://twitter.com/xelfer

paginate:         10



